### ISSUE TITLE
Grillplats i kommuns data som har dåligt skick

### ISSUE THREAD

**Issue by salgo60** [dpriskorn/svenska-grillplatser#46]
*  [ChatGPT om hur status förändringar över tid skall beskrivas](https://github.com/dpriskorn/svenska-grillplatser/issues/46#issuecomment-2365123149)

<img width="826" alt="image" src="https://github.com/user-attachments/assets/13e888be-40fc-4232-ac6d-6702801afe1c">

WD https://www.wikidata.org/wiki/Q121536695 / [Wikicommons Grillplatser Lidingö](https://commons.wikimedia.org/wiki/Category:Grillplatser_Liding%C3%B6)

OSM anteckning https://www.openstreetmap.org/note/3838263

Grillplatser.nu https://grillplatser.nu/Grillplats/Visa/Kappsta

https://www.lidingo.se/toppmeny/kulturfritid/friluftsliv/grillplatserochvindskydd.4.1692b2a2121d0e1fbcb800012.html

Jag vill se att vi kan logga ett ärende hos Lidingö kommun där vi kan följa 
1) deras beslut
2) att dom tar bort den på hemsida och öppna data
3) att dom i sitt öppna data hanterar även borttagna grillplatser typ från/till/orsak
3-1) är man kunnig så görs det med [PROV](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/167)

![image](https://github.com/user-attachments/assets/034af08d-c1e8-4313-bd25-ead0797a3fdf)

Fundering eftersom detta aldrig diskuteras när man pratar öppna data hur stort är nyttan och användningen?

----
### Lidingö Grillplatser

* [OSM](https://overpass-turbo.eu/map.html?Q=++area%5B%22name%22%3D%22Liding%C3%B6+kommun%22%5D-%3E.boundaryarea%3B%0A++%28%0A++nwr%28area.boundaryarea%29%5B%22leisure%22%3D%22firepit%22%5D%3B%0A++nwr%28area.boundaryarea%29%5B%22amenity%22%3D%22bbq%22%5D%3B%0A%0A++%29%3B%0A+out+meta%3B) 

<img width="560" alt="image" src="https://github.com/user-attachments/assets/9f57f47a-e3a8-4d58-bf14-b18c6ae41350">

* [Kommunens data ](https://karta.lidingo.se/spatialmap?selectorgroups=bakgrund+kulturfritid&mapext=149412+6577568+173988+6590432&layers=theme-lm_topo+theme-grill_vindskydd&mapheight=1010&mapwidth=1925&label=&ignorefavorite=true&profile=baskarta_extern)

<img width="1118" alt="image" src="https://github.com/user-attachments/assets/01971391-9d93-43c2-a93f-5b8ef3d5a5dd">

* [Grillplatser.nu](https://grillplatser.nu/Kommun/Liding%C3%B6#google_vignette)

<img width="953" alt="image" src="https://github.com/user-attachments/assets/fd4ff6e9-dc05-4286-b731-a2b650bdc2f2">

* [Wikidata Grillplatser Lidingö kommun](https://w.wiki/BGaD) 

<img width="693" alt="image" src="https://github.com/user-attachments/assets/e7d9a2db-72d0-4b11-897a-b2667eca864c">

* [OSM Anteckning 3838263](https://www.openstreetmap.org/note/3838263)

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/59ecc629-f414-4c32-a0d7-8dd659a98e95">

**Comment by salgo60** [comment]
Är det rätt plats? Har skrivit om att grillplatser, badplatser borde ha QRCkoder som kopplar dom till sin digitala motsvarighet... --> skulle göra det enkelare att felanmäla osv. se när kommunen senast besökte den och kanske fyllde på ved(kan vara känsligt) jmf OSM [check_date](https://wiki.openstreetmap.org/wiki/Key:check_date)

Kollar på Kappsta https://www.lidingo.se/toppmeny/kulturfritid/friluftsliv/grillplatserochvindskydd.4.1692b2a2121d0e1fbcb800012.html 
* gissar samma som [Q121536540](https://www.wikidata.org/wiki/Q121536540) / https://grillplatser.nu/Grillplats/Visa/Kapsta

![image](https://github.com/user-attachments/assets/7394776f-e2bd-4a36-b714-723b7089e5b5)

**Comment by salgo60** [comment]
Grillplats som försvunnit ?!?! https://www.openstreetmap.org/note/3841587

https://grillplatser.nu/Grillplats/Visa/Larsbergsparken

https://www.wikidata.org/wiki/Q121603429

Är inte säker på att Lidingö kommun har bra identifierare för sina objekt? Tyvärr är dom inte ensamma det bästa vi ser är typ Härryda kommun #43

**Comment by salgo60** [comment]
[ChatGpt](https://chatgpt.com/share/66eea0eb-31d0-800a-b414-477cd68f5e99) - saknar att [DIGGs persistent-identifiers-investigation](https://github.com/diggsweden/persistent-identifiers-investigation/issues/4#issuecomment-1729126931) ([IA](https://web.archive.org/web/20240922083311/https://github.com/diggsweden/persistent-identifiers-investigation/issues/4#issuecomment-1729126931)) tar tag i livscykeln eller ens funderar över [arkivering](https://github.com/diggsweden/persistent-identifiers-investigation/issues/23) - samma fråga [Riksarkivet #17](https://github.com/Riksarkivet/dataplattform/issues/17) ([IA](https://web.archive.org/web/20240327081945/https://github.com/Riksarkivet/dataplattform/issues/17))

**ChatGPT** Jag har tidigare diskuterat en spec om kommunens [nämndeärenden](https://github.com/salgo60/Anslagstavla/issues/43) med dig där jag vill se mer kopplingar till processer ([antipattern #77-9 saknas processtänk](https://github.com/salgo60/DIGG-skuggbacklog/issues/77#issuecomment-1310334500))…. Lagar byggnader typ [Eli:is_about](http://publications.europa.eu/resource/cellar/16bfefd0-64a9-11eb-aeb5-01aa75ed71a1.0001.02/DOC_1)

Nu tittar vi på enormt enkel data om grillplatser som många kommuner klara av att skapa med fält
* namn
* koordinat
* kommun

**Det vi saknar är ett livscykel tänk**
* en grillplats som tas bort ett visst datum
* en grillplats som är en dublett
* en grillplats som fortfarande är en grillplats men inte uppfyller kraven på en kommunal grillplats

Jag har pratat om **[PROV](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/167)** för forskningsdata och tror samma behövs för all information som har en livscykel som grillplatser men även nämnde ärenden hör hit

#### Tombstone
Annat bra mönster är [tombstone](https://github.com/diggsweden/persistent-identifiers-investigation/issues/13) sidor dvs. det datacite pratar om https://support.datacite.org/docs/tombstone-pages

Tankar om detta och ge exempel hur det skall visas för grillplatser

<img width="1011" alt="image" src="https://github.com/user-attachments/assets/10e655e4-4078-49b6-93aa-2620944bd3dd">


----

![image](https://github.com/user-attachments/assets/3146e2d8-0ade-4ad2-9369-de6f3d18d411)

![image](https://github.com/user-attachments/assets/884e35a3-46ed-4dbb-96b5-bb1da3c729e6)

**Comment by salgo60** [comment]
Tycker ovanstående resonemang om aktivitet/ beslut koppling borde synas i specar om nämdeärenden [länk](https://github.com/salgo60/Anslagstavla/issues/43)

**Comment by dpriskorn** [comment]
> Tycker ovanstående resonemang om aktivitet/ beslut koppling borde synas i specar om nämdeärenden [länk](https://github.com/salgo60/Anslagstavla/issues/43)

Enig. Vi är ljusår från att ha bra data från kommunerna. 
Jag har försökt använda min lokala kommuns app för rapportering av avvikelser. 
De svarar sen via epost utan ett vettigt ärendenummer.
Grillplatserna verkar inte ha persistenta ID
Ingen verkar ha överblick eller kvalitetssäkra dem heller.

**Comment by salgo60** [comment]
@dpriskorn när vi skickade internationella banktransaktioner hade vi SWIFT meddelande som kommunicerade överföring, fråga status etc. för banktransaktioner -  flera [100 olika meddelande](https://www.paiementor.com/list-of-all-swift-messages-types/) **vet inte hur vi skall komma dit** känns inte som vi ens förstår problemet

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/8e9fa241-3ccf-4773-822e-06acb08532c6">
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/2278c683-fb65-4792-9676-0be68bcd49fd">
<img width="1097" alt="image" src="https://github.com/user-attachments/assets/70211cdc-531b-4c78-a111-05b9a1059306">
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/037c3121-e553-42af-a668-d1d92c4b6949">
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/6dcfeaa6-9ec3-4032-b389-198b793e3554">
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/194b68ce-60b0-4e58-b129-7ed905c50b89">
<img width="1096" alt="image" src="https://github.com/user-attachments/assets/da6489ef-d7d5-43e7-bc1c-a36408fba1bd">
<img width="1066" alt="image" src="https://github.com/user-attachments/assets/f78b2dfe-541c-413c-a4f3-a56794b447d0">
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/ace346dc-dfa7-47fd-88a1-fea5448302eb">
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/946c739f-139d-43ab-bc72-098ac5324e31">

**Comment by salgo60** [comment]
Intressant problem jag hitta på [WIkidata med sjöar som pekar fel](https://sv.wikipedia.org/wiki/Wikipedia:Wikidatafr%C3%A5gor#Fel_i_Wikidata) vi får se om det löses där vi har fel i VISS data [waterEUID=SE671949-141644](https://viss.lansstyrelsen.se/Waters.aspx?waterEUID=SE671949-141644) som pekar på fel sjö...

<img width="1051" alt="image" src="https://github.com/user-attachments/assets/e631b7fd-8789-4844-ad67-08f1ae02943b">

### Wikidata hjältar som försöker styra upp detta
* [WIkidata med sjöar som pekar fel](https://sv.wikipedia.org/wiki/Wikipedia:Wikidatafr%C3%A5gor#Fel_i_Wikidata)

<img width="1271" alt="image" src="https://github.com/user-attachments/assets/9a1742c3-0ff4-41d3-b3a8-c43220e8796a">

<img width="1238" alt="image" src="https://github.com/user-attachments/assets/9e550c07-ee55-42fd-bb24-f726dc7a2745">

**Comment by salgo60** [comment]
## Mapillary Kappsta - grillplats eller inte grillplats

Tanken är att vandra runt i Kappsta och få ytterliggare än "källa" til status [OSM Anteckningar](https://www.openstreetmap.org/note/3838263) är bra men Mapillary känns som [ytterliggare en nivå](https://www.openstreetmap.org/note/3838263)

[Status Mapillary 2024 09 22](https://www.mapillary.com/app/?lat=59.34242090121435&lng=18.1678999092818&z=14.52768709805683)

<img width="1355" alt="image" src="https://github.com/user-attachments/assets/15e5279d-2f25-4632-83f1-039f785b4b64">

<img width="1281" alt="image" src="https://github.com/user-attachments/assets/df46606d-ecfd-48b9-8433-c6f878f8c8ea">

* https://www.mapillary.com/app/?lat=59.340986701753565&lng=18.166988196357124&z=15.84122671446442&pKey=1507768039844980

**Comment by salgo60** [comment]
Var på plats den känns så där... 
1) la upp en bild på [grillplatser.nu](https://grillplatser.nu/Grillplats/Visa/Kappsta) om han vill ha platsen
2) stänger OSM Note [3838263](https://www.openstreetmap.org/note/3838263) utan att skapa **OSM node** 
* [Mapillary 1507768039844980](https://www.mapillary.com/app/?pKey=1507768039844980&lat=59.340184804434&lng=18.168897454529&z=17)
* WD [Q121536695](https://www.wikidata.org/wiki/Q121536695?uselang=sv)
* [grillplatser.nu](https://grillplatser.nu/Grillplats/Visa/Kappsta)
3) OSM user [bagis](https://www.openstreetmap.org/user/bagis) har kommunicerat platsen dåliga skick med Lidingö kommun

<img width="302" alt="image" src="https://github.com/user-attachments/assets/0b8e53c3-0d21-4e10-9824-12341e24705c">


<img width="299" alt="image" src="https://github.com/user-attachments/assets/e4ffd144-4c00-49e9-ad0d-06830d9fbab2">

**Comment by salgo60** [comment]
Intressant hur Lidingö kommun [klumpar ihop grillplatserna och att inte varje grillplats har ett eget unikt id](https://github.com/dpriskorn/svenska-grillplatser/issues/6#issuecomment-1683492953)

<img width="882" alt="image" src="https://github.com/user-attachments/assets/c37bba24-72b5-4ca8-8078-05cb6ea4730c">

**Comment by salgo60** [comment]
* Lidingö kommuns öppna data [www.dataportal.se/datasets/238_39760](https://www.dataportal.se/datasets/238_39760) uppdaterat 22 jan 2024 - [json](https://ckan-storsthlm.dataplattform.se/dataset/grillplatser/resource/a3660a67-6ae7-4347-98fa-3f98f2d75526/download/grillplatser.json)https://[ckan-storsthlm.dataplattform.se/dataset/grillplatser/resource/a3660a67-6ae7-4347-98fa-3f98f2d75526/download/grillplatser.json](https://ckan-storsthlm.dataplattform.se/dataset/grillplatser/resource/a3660a67-6ae7-4347-98fa-3f98f2d75526/download/grillplatser.json)

* Kappsta i datat
   * **samma som saknas**
<img width="531" alt="image" src="https://github.com/user-attachments/assets/df3aedcf-2ee0-4eca-a68b-492ec5dfea3b">

<img width="433" alt="image" src="https://github.com/user-attachments/assets/8db7406a-3871-4de2-96cc-d7dc9882a5e4">

<img width="436" alt="image" src="https://github.com/user-attachments/assets/edcf69b3-b263-438f-9bcf-8fe1885c9e29">


* Gist [json](https://gist.github.com/salgo60/a9142c2857e2acd71a35b6dc5e9be503)

<img width="753" alt="image" src="https://github.com/user-attachments/assets/f723374f-dd61-44d1-8c25-8a14cd8357fc">

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/17f23c96-d8b2-4c63-af1a-7ee5477deb53">
